/***
 *  File: a5.cpp
 *  Author: Jaroslaw Zola <jzola@buffalo.edu>
 */

// DO NOT EDIT THIS FILE !!!
// YOUR CODE MUST BE CONTAINED IN a5.hpp ONLY

#include "token.hpp"
#include "a5.hpp"

#include <iostream>
#include <vector>

int main(int argc, char* argv[]) {
    std::vector<token> tokens;

    std::string s;
    while (std::cin >> s) tokens.push_back(to_token(s));

    // your code is invoked here
    try {
        double d = RPN(tokens.begin(), tokens.end());
        std::cout << d << std::endl;
    } catch (...) {
        std::cout << "error" << std::endl;
    }

    return 0;
} // main
